language: c
dist: trusty
sudo: false

# Based on https://github.com/greghendershott/travis-racket


env:
  global:
    - RACKET_DIR=~/racket
  matrix:
    - RACKET_VERSION=6.8
    - RACKET_VERSION=6.9
    - RACKET_VERSION=6.10
    - RACKET_VERSION=HEAD
matrix:
  allow_failures:
    - env: RACKET_VERSION=HEAD

before_install:
# install racket
- git clone https://github.com/greghendershott/travis-racket.git ~/travis-racket
- cat ~/travis-racket/install-racket.sh | bash # pipe to bash not sh!
- export PATH="${RACKET_DIR}/bin:${PATH}" # install-racket.sh can't set for us
# install rosette
- raco pkg install --no-setup rosette  # install rosette without compiling its docs
- raco setup -Dl rosette
# install typed rosette
- git clone https://github.com/stchang/typed-rosette ~/typed-rosette
- raco pkg install ~/typed-rosette

install:
 - raco pkg install --deps search-auto

script:
 - raco test -x -p ocelot

after_success:
 - raco setup --check-pkg-deps --pkgs ocelot
